export * from "./events-list.component";
export * from "./event-thumbnail.component";
export * from "./edit-event.component";
export * from "./create-event.component";
export * from "./event-details/event-details.component";
export * from "./event-details/create-session.component";
export * from "./event-details/session-list.component";
export * from "./shared/event.service";
export * from "./shared/event-route-activator.service";
export * from "./shared/event-resolve.service";
export * from "./shared/event.model"
export * from "./shared/duration.pipe";